### PR TITLE
fix - Unsupported class file for the build action class

### LINKED ISSUE #169: The compile of build action
We introduced the build action to solve composite build in #154. There is a problem that the build action class is in the server project, which is compiled by jdk 17. But in real, the build action class runs inside the gradle daemon, so if the gradle daemon is not running on jdk >= 17, error like `Unsupported class file major version 61` will be thrown.

Looks like we should move `GetSourceSetsAction` into the `model` module.

I guess this is something we need to do before the parallel work @Arthurm1. I'll raise a PR soon.

### PR DESCRIPTION
**Pull request by jdneo**
- Move the GetSourceSetsAction class to the model module, to ensure that the GetSourceSetsAction class is compiled on level 1.8.
- Set the required properties to the BuildActionExecuter.

fix #169

### CODE REVIEW

**Comment by jdneo** [comment]
_// cc @Tanish-Ranjan, @Arthurm1_

**Comment by Arthurm1** [comment]
LGTM - makes sense to have the action in the `Model` project.  I'd possibly go further and set the java version for `server` and `plugin` to 8 as well since the 17 features are hardly used and then more JDK versions are supported, but it's not for this PR.

**Comment by jdneo** [comment]
>  I'd possibly go further and set the java version for server and plugin to 8 as well

the plugin is already 8 now: https://github.com/microsoft/build-server-for-gradle/blob/develop/plugin/build.gradle#L19. Server is now on 17. Yes making it on 8 will expand the usage. But some refactoring needs to be done. I can do that in another PR.

**Comment by Tanish-Ranjan** [comment]
I have a different thought on this. The `Model` module only contains model classes which are used by `Plugin` and `Server`. It made the most sense for me to have the BuildAction in the `Server` functionality vise, although as you pointed out, we have a slight catch, that the BuildActions are executed within the Gradle Daemon.

So, I would add this to changes:
- renaming the `Model` module to `Internal` (Something being used internally by both `Plugin` and `Server`) as it is no longer dedicated for models only.

**Comment by jdneo** [comment]
@Tanish-Ranjan We can put it a debt. I'll discuss this with Donat to see what's the best answer.

For now, maybe we can merge this change first and release an updat. (I observed this problem because I saw the import success rate drop down from the BI)

**Review by testforstephen — APPROVED** [review]

**Pull request merged**
