### PR TITLE
fix - Use project dir instead of project path

### PR DESCRIPTION
**Pull request by jdneo**
- In composite build scenario, the project path is not based on the build tree root. Besides, the .getBuildTreePath() is not available before Gradle 8.3, we use the project dir to identify a Gradle project instead. The project dir is used in dependency resolution.

Fix the point 2 in https://github.com/microsoft/build-server-for-gradle/pull/154#issuecomment-2219647109

### CODE REVIEW

**Comment by jdneo** [comment]
// cc @Tanish-Ranjan, @Arthurm1

**Comment by Arthurm1** [comment]
So `project.getPath()` is not unique when using included builds?  We might need to also look at what goes into `gradleSourceSet.setDisplayName`.  It might be better to do in the action after full retrieval.  Maybe set display name to full path and then pare it down to differences in the build action?
I did something similar [here](https://github.com/scalacenter/gradle-bloop/blob/506dc933d0148abe6bfe88f477db9e9d1b0fdf07/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L825).  I can look to reproduce in another PR?

**Comment by jdneo** [comment]
> So project.getPath() is not unique when using included builds?

No they are not. In the sample project that I referenced, both project path is `:`.

> It might be better to do in the action after full retrieval. Maybe set display name to full path and then pare it down to differences in the build action?
I did something similar [here](https://github.com/scalacenter/gradle-bloop/blob/506dc933d0148abe6bfe88f477db9e9d1b0fdf07/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L825). I can look to reproduce in another PR?

Sure, feel free to address it in another PR if you want :)

**Comment by Tanish-Ranjan** [comment]
> So project.getPath() is not unique when using included builds?

It won't. Any information that comes from the `project` will be stripped down to the [rootProject](https://github.com/microsoft/build-server-for-gradle/blob/3b691da501a9b9f7a2f0df84e726ba4187725573/plugin/src/main/java/com/microsoft/java/bs/gradle/plugin/SourceSetsModelBuilder.java#L49). `SourceSetsModelBuilder` considers the project it receives in the `buildAll` parameter, to be the root project. This is why we had to resort to `BuildActions` in #154, as it contains the complete information of the project hierarchy. It queries for each sub project in the build. This is where the `SourceSetsModelBuilder` starts building the requested model unaware of the entire project hierarchy and thinks the sub project we are querying is actually the root project.

Now because of the way model builders work we cannot rely on hierarchical information from it, such as project path.

Hope I explained it well. Please ask any questions if you have queries.

**Comment by jdneo** [comment]
Another solution is to get the build tree path by casting the `Project` to `DefaultProject`, and call `getIdentityPath()`. But that is an internal API, and since the project dir works fine for now, we can use project dir currently.

Just to share this information in case we need to revisit this problem in the future.

**Review by testforstephen — APPROVED** [review]

**Pull request merged**
