### PR TITLE
Update project to use Gradle 8.7

### PR DESCRIPTION
**Pull request by Arthurm1**
Updates Gradle from 8.1 to 8.7 so jdk 21 can be used to develop

I've left the buildship version as is so some tests will fail unless JDK 17 or lower is used to run them.  Can this also be changed or is it set to 7.4.2 for a reason...
https://github.com/microsoft/build-server-for-gradle/blob/ec53a53b8b2b66cad5303e09474010b39d9303ff/server/src/main/java/com/microsoft/java/bs/core/internal/gradle/Utils.java#L45

### CODE REVIEW

**Comment by jdneo** [comment]
They are some stale(invalid) checks. I'll raise a PR to remove them.

**Comment by jdneo** [comment]
Removed in https://github.com/microsoft/build-server-for-gradle/pull/137

**Comment by jdneo** [comment]
> I've left the buildship version as is so some tests will fail unless JDK 17 or lower is used to run them.

Which tests?

**Comment by Arthurm1** [comment]
> Which tests?

`testJavaCompilerArgsToolchain` failed for me but I think that's because I was switching between jdk-17 and jdk-21.  All work now.

**Review by jdneo — APPROVED** [review]

**Comment by jdneo** [comment]
Thank you @Arthurm1 for your contribution!

**Pull request merged**
