### PR TITLE
Add jdk 22 compatibility

### PR DESCRIPTION
**Pull request by Arthurm1**
Gradle supports JDK 22 from version 8.7

https://docs.gradle.org/current/userguide/compatibility.html

### CODE REVIEW

**Comment by jdneo** [comment]
Since the column `Support for running Gradle` is still N/A, I think we need to wait more...

**Comment by Arthurm1** [comment]
Ah - my mistake

**Comment by jdneo** [comment]
https://docs.gradle.org/current/userguide/compatibility.html

8.8 supports java 22. Would you like to reopen this ?

**Comment by jdneo** [comment]
Never mind, I'll take it: https://github.com/microsoft/build-server-for-gradle/pull/152

**Pull request closed without merging**
